spring:
  application:
    name: member

  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"

  cloud:
    config:
      name: member
      profile: ${SPRING_PROFILES_ACTIVE:local}
