version: "3"
services:
  frontend-blue:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend-blue
    ports:
      - "3000:80"
    networks:
      - webnet
    restart: always

  # eureka, api-gateway는 blue-blue 전략을 사용하지 않는다.
  eureka-server-blue:
    build:
      context: ./back/eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - webnet
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  api-gateway-blue:
    build:
      context: ./back/gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
    networks:
      - webnet
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  # payment / blue, blue
  payment-blue:
    build:
      context: ./back/payment
      dockerfile: Dockerfile
    container_name: payment-blue
    ports:
      - "18010:8080"
    networks:
      - webnet
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_PROFILES_COLOR=blue

  # moapay / blue, blue
  moapay-blue:
    build:
      context: ./back/moapay
      dockerfile: Dockerfile
    container_name: moapay-blue
    ports:
      - "18020:8080"
    networks:
      - webnet
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_PROFILES_COLOR=blue

  # settlement / blue, blue
  settlement-blue:
    build:
      context: ./back/settlement
      dockerfile: Dockerfile
    container_name: settlement-blue
    ports:
      - "18030:8080"
    networks:
      - webnet
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_PROFILES_COLOR=blue

  # member / blue, blue
  member-blue:
    build:
      context: ./back/member
      dockerfile: Dockerfile
    container_name: member-blue
    ports:
      - "18040:8080"
    networks:
      - webnet
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_PROFILES_COLOR=blue

  # notification / blue, blue
  # notification-blue:
  #   build:
  #     context: ./back/notification
  #     dockerfile: Dockerfile
  #   container_name: notification-blue
  #   ports:
  #     - "18061:8080"
  #   networks:
  #     - webnet
  #   depends_on:
  #     - eureka-server
  #     - api-gateway
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod

  # cardbank는 moapay 서비스가 아니므로, blue-blue 전략을 사용하지 않는다.
  cardbank-blue:
    build:
      context: ./back/cardbank
      dockerfile: Dockerfile
    container_name: cardbank
    ports:
      - "18100:8080"
    networks:
      - webnet
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  # store는 moapay 서비스가 아니므로, blue-blue 전략을 사용하지 않는다.
  store-blue:
    build:
      context: ./back/store
      dockerfile: Dockerfile
    container_name: store
    ports:
      - "18200:8080"
    networks:
      - webnet
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

networks:
  webnet:
    external: true
